server:
  port: 8080

spring:
  application:
    name: zidongxiche

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url:  jdbc:mysql://127.0.0.1:3306/car_wash_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zdxc.entity